# Generated by Django 2.2.1 on 2019-10-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.IntegerField()),
                ('company', models.CharField(max_length=32)),
                ('message', models.TextField()),
            ],
        ),
    ]
